name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  pipeline:
    uses: shed-os/shedos-ci/.github/workflows/package-pipeline.yml@main
    with:
      packages: '["."]'
    secrets:
      SHEDOS_DISPATCH_TOKEN: ${{ secrets.SHEDOS_DISPATCH_TOKEN }}
